let productsDB = [
    {id:1,
    title: "headphone item",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    size: 'large',
    imageUrl: 'images/head.jpg',
    qty: 1,
    isMe: "N",
    } ,
    {id:2,
        title: "labtop item",
            desc: "Lorem ipsum dolor sit amet consectetur.",
        size: 'small',
        imageUrl: 'images/lap.jpg',
        qty: 1,
        isMe: "N",
        },
    {id:3,
            title: "sunglass item",
            desc: "Lorem ipsum dolor sit amet consectetur.",
            size: 'mediem',
            imageUrl: 'images/sun.jpg',
            qty: 1,
            isMe: "N",
            },
            {id:4,
                    title: "note item",
                    desc: "Lorem ipsum dolor sit amet consectetur.",
                    size: 'mediem',
                    imageUrl: 'images/note.jpg',
                    qty: 1,
                    isMe: "N",
                    },
];

// localStorage.setItem("products", JSON.stringify(productsDB));
